Create Git y GitHub
atralice/Curso.Prep.Henry pull request #103
Opened 2021-08-03 15:41 UTC by Douglas-san-anton

Muchas gracias por la oportunidad!!
Si hay que retocar algo avísame..

2021-08-03 15:47 UTC, atralice submitted a review, later dismissed

2021-08-03 15:53 UTC, GustavoMartinezFS commented on 01-Git/Git y GitHub.md
> +    - git commit - m "versión 1": aqui se guardan cambios de "Staging Area" y con ( -m "") se deja un mensaje que nos sea util.
solamente juntar el guion - con la m, para no confundir

2021-08-03 15:55 UTC, GustavoMartinezFS commented on 01-Git/Git y GitHub.md
> +    - git add + "el archivo": crea el archivo pero no lo guarda de forma definitiva, lo almacena en (Staging Area).
Creo que seria mejor poner git add ArchivoEjemplo.js  para evitar malos entendidos

2021-08-03 15:57 UTC, Douglas-san-anton commented on 01-Git/Git y GitHub.md
> +    - git commit - m "versión 1": aqui se guardan cambios de "Staging Area" y con ( -m "") se deja un mensaje que nos sea util.
Perfecto ahí esta, Muchas gracias!!

2021-08-03 16:03 UTC, Douglas-san-anton commented on 01-Git/Git y GitHub.md
> +    - git add + "el archivo": crea el archivo pero no lo guarda de forma definitiva, lo almacena en (Staging Area).
Cambio realizado, ahí si queres que retoque algo mas me avisas, siempre estoy pendiente!

2021-08-03 16:52 UTC, Douglas-san-anton reviewed
Ahi esta, gracias!

2021-08-05 14:22 UTC, atralice approved these changes

2021-08-08 23:50 UTC, GustavoMartinezFS approved these changes

2021-08-10 01:15 UTC, aghmnl requested changes

2021-08-17 18:53 UTC, merged