HH's
atralice/Curso.Prep.Henry pull request #60
Opened 2021-04-23 13:52 UTC by Mate444

Hola soy uno de los HH's, entendi que Agus decia que hagamos un pull request del repo del prep!

2021-04-23 14:28 UTC, atralice commented
Buenas, Mateo!
Sip, pero para mejorar/corregir ciertas cosas del repo. Ahi me fijé y en el PR estás subiendo soluciones tmb. Revisá eso.

Abrazo.

2021-04-23 14:28 UTC, atralice requested changes
No hay que subir las soluciones en este repo.

2021-04-26 18:25 UTC, Mate444 commented
bien, disculpas ahora lo acomodo

On Fri, Apr 23, 2021 at 11:28 AM Toni Tralice ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> No hay que subir las soluciones en este repo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atralice/Curso.Prep.Henry/pull/60#pullrequestreview-643359072>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARN7QBFSV4G3AFUY5DLN2OLTKF7Z3ANCNFSM43OWDORA>
> .
>

2021-04-27 22:30 UTC, atralice requested changes
Todavía hay soluciones. Y fijate que hay muchos mini cambios tmb (faltan comentarios, o hay saltos de líneas de más).
Te conviene hacer un checkout de todo menos el único archivo que tenga modificaciones postas.

2021-06-03 17:27 UTC, atralice requested changes
Buenas! fijate que no dejaste igual cómo estaba.
Borraste las consignas de los ejercicios.

2021-06-03 17:35 UTC, Mate444 commented
Ahora las arreglo


On Thu, Jun 3, 2021 at 2:27 PM Toni Tralice ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Buenas! fijate que no dejaste igual cómo estaba.
> Borraste las consignas de los ejercicios.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atralice/Curso.Prep.Henry/pull/60#pullrequestreview-675549621>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARN7QBDCSECWOOA3FPNRQE3TQ63QFANCNFSM43OWDORA>
> .
>

2021-06-22 19:01 UTC, closed without merging

2021-06-22 20:44 UTC, waku10 commented
Hola buenas tardes . Termine la tarea de JSI. Donde lo envio o que temgo que hacer para q lo vean?